# Generated by Django 3.0.6 on 2020-05-12 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('in_tehran', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('insurance_sts', models.CharField(max_length=120)),
                ('insurance_no', models.CharField(max_length=120)),
                ('bank_account', models.CharField(max_length=120)),
                ('bank_card_number', models.CharField(max_length=120)),
                ('intro_checklist', models.CharField(max_length=120)),
                ('equip_checklist', models.CharField(max_length=120)),
                ('sts', models.CharField(choices=[('Active', 'پذیرفته شده'), ('InActive', 'بررسی نشده'), ('Failed', 'رد شده')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncode', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('jobs', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
                ('is_global', models.BooleanField(default=False)),
                ('for_cities', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('iden_id', models.CharField(max_length=120)),
                ('iden_serial', models.CharField(max_length=120)),
                ('iden_place', models.CharField(max_length=120)),
                ('birth_place', models.CharField(max_length=120)),
                ('birth_date', models.CharField(max_length=120)),
                ('marriage_sts', models.CharField(max_length=120)),
                ('house_sts', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('phone_emergency', models.CharField(max_length=120)),
                ('sts', models.CharField(choices=[('Active', 'پذیرفته شده'), ('InActive', 'بررسی نشده'), ('Failed', 'رد شده')], max_length=10)),
                ('phone_emergency_name', models.CharField(max_length=120)),
                ('phone_emergency_related', models.CharField(max_length=120)),
                ('commitment_file_id', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('interviewer', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('score', models.CharField(max_length=120)),
                ('result', models.CharField(max_length=120)),
                ('note', models.CharField(max_length=120)),
                ('sts', models.CharField(choices=[('Active', 'پذیرفته شده'), ('InActive', 'بررسی نشده'), ('Failed', 'رد شده')], max_length=10)),
                ('interview_at', models.CharField(max_length=120)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Personnel')),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relation', models.CharField(max_length=120)),
                ('edu_level', models.CharField(max_length=120)),
                ('edu_title', models.CharField(max_length=120)),
                ('job', models.CharField(max_length=120)),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('trend', models.CharField(max_length=120)),
                ('university', models.CharField(max_length=120)),
                ('start_at', models.CharField(max_length=120)),
                ('end_at', models.CharField(max_length=120)),
                ('file_id', models.CharField(max_length=120)),
                ('note', models.CharField(max_length=120)),
                ('level', models.CharField(max_length=120)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Personnel')),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=120)),
                ('score_var', models.CharField(max_length=120)),
                ('note', models.CharField(max_length=120)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Personnel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('salary', models.SmallIntegerField()),
                ('worker_coupon', models.CharField(max_length=120)),
                ('housing_allowance', models.CharField(max_length=120)),
                ('right_attraction', models.CharField(max_length=120)),
                ('right_guardianship', models.CharField(max_length=120)),
                ('reason_termination', models.CharField(max_length=120)),
                ('contract_file_id', models.CharField(max_length=120)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Personnel')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='proposal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proposal'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('data', models.DateTimeField()),
                ('created_at', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=120)),
                ('filename', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
